"""Probe the candidate axioms (W5), (W5') on the class generated by tree/constant cells under substitution and legs.
For a fixed cell, over many trees/heights (including near-degenerate ones) and windows, record
  r1 = (E-S) / min(E - hp, E_anc - S_anc)   [root-run: (E-S)/(v-u)]   -> should be bounded below (per cell)
  r2 = (E_anc - E) / (E - S)                                             -> should be bounded above (per cell)."""
import random, math
from partitions import *
from trees import *
from cuts import *
from wcs import *
random.seed(11)

def random_labelling(flag):
    l = len(flag) - 1; e = {}
    for j in range(l - 1):
        for B in flag[j]:
            pp = parent_position(flag, (j, B)); lo = 0.0 if pp is None else e[pp]
            e[(j, B)] = lo + (1 - lo) * (0.2 + 0.6 * random.random())
    return e

def squeeze(F, h):
    """Random near-degenerate perturbation: push some blocks to their parents or to 1."""
    h = dict(h)
    for B in internal(F):
        r = random.random()
        p = parent(F, B)
        if r < 0.25 and p is not None:
            h[B] = h[p] + 10 ** (-random.randint(1, 7)) * (h[B] - h[p])
        elif r < 0.4:
            h[B] = 1 - 10 ** (-random.randint(1, 7)) * (1 - h[B])
    # restore order-preservation downward
    def fix(B, lo):
        if len(B) == 1: return
        h[B] = max(h[B], lo)
        for C in children(F, B): fix(C, h[B])
    fix(root(F), 0.0)
    return h

def ratios(cell, F, h, u, v):
    out = []
    for pos in nonunary(cell.flag):
        S, E = cell.frames(F, h, pos, u, v)
        w = E - S
        a = anchor(cell.flag, pos)
        hpB = hp(F, h, pos[1], u)
        if a is None:
            rhs = v - u; d = None
        else:
            Sa, Ea = cell.frames(F, h, a, u, v)
            rhs = min(E - hpB, Ea - Sa); d = Ea - E
        r1 = None if rhs <= 1e-12 else w / rhs
        r2 = None if (d is None or d <= 1e-12) else (math.inf if w <= 1e-15 else d / w)
        out.append((pos, r1, r2, w, rhs, d))
    return out

report = {}
for n in (3, 4, 5):
    T = frozenset(range(n))
    for F in all_trees(T):
        h0 = random_weighting(F); chain, _ = theta_inverse(F, h0); k = len(chain) - 1
        if k < 3: continue
        for _ in range(2):
            L = random.randint(3, k); mids = sorted(random.sample(range(1, k), L - 1))
            merged = (chain[0],) + tuple(chain[i] for i in mids) + (chain[-1],)
            j = random.randint(1, L - 1); lp = min(random.randint(2, L), L - j + 1)
            of = merged[:j] + merged[j + lp - 1:]
            def mk(kind, flag):
                c = constant_cell(flag, random_labelling(flag))
                return {"tree": tree_cell(flag), "const": c, "leg1": leg1_cell(c), "leg2": leg2_cell(c, 0.5),
                        "leg3": leg3_cell(c, 0.5), "leg2b": leg2_cell(c, 0.9), "leg3b": leg3_cell(c, 0.1)}[kind]
            kinds = ["tree", "const", "leg1", "leg2", "leg3", "leg2b", "leg3b"]
            cells = {}
            for ko in kinds:
                for ki in kinds:
                    inner = {(j - 1, B): mk(ki, inner_flag_at(merged, j, lp, (j - 1, B))) for B in of[j - 1]}
                    cells[f"{ko}*{ki}"] = substitute(mk(ko, of), j, inner)
            for kind in kinds:
                cells[kind] = mk(kind, merged)
            for name, cell in cells.items():
                r1min, r2max = math.inf, 0.0
                for _ in range(6):
                    h = random_weighting(F)
                    if random.random() < 0.7: h = squeeze(F, h)
                    u, v = (0.0, 1.0) if random.random() < 0.5 else (random.random() * 0.3, 0.7 + random.random() * 0.3)
                    hh = {B: u + (v - u) * x for B, x in h.items()}
                    for pos, r1, r2, w, rhs, d in ratios(cell, F, hh, u, v):
                        if r1 is not None: r1min = min(r1min, r1)
                        if r2 is not None: r2max = max(r2max, r2)
                rec = report.setdefault(name, [math.inf, 0.0])
                rec[0] = min(rec[0], r1min); rec[1] = max(rec[1], r2max)
for name in sorted(report):
    r1, r2 = report[name]
    print(f"{name:12s}  min r1 = {r1:10.3e}   max r2 = {r2:10.3e}")
